services:
  - type: web
    name: ai-skillpath-backend
    env: node
    region: singapore # or oregon, frankfurt, etc.
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
